### ISSUE TITLE
Tests fail on master (ba1b63eb769693bf63b1e184cd3245388f590e12)

### ISSUE THREAD

**Issue by thesamesam** [rui314/mold#137]
Full log here: [build.log](https://github.com/rui314/mold/files/7716917/build.log)

Tests fail for me:
```
>>> Source compiled.
>>> Test phase: sys-devel/mold-9999
make -j24 SYSTEM_TBB=1 SYSTEM_MIMALLOC=1 check 
make -C test -f Makefile.linux --no-print-directory --output-sync
Testing aarch64-hello-static ... skipped
Testing cmdline ... OK
Testing auxiliary ... OK
Testing basic ... make[1]: *** [Makefile.linux:6: elf/basic.sh] Error 1
make[1]: *** Waiting for unfinished jobs....
Testing discard ... OK
Testing copyrel ... OK
Testing copyrel-relro ... OK
Testing copyrel-protected ... OK
Testing canonical-plt ... OK
Testing ar-alignment ... bfd plugin: LLVM gold plugin has failed to create LTO module: The end of the file was unexpectedly encountered
OK
Testing bsymbolic ... OK
Testing common-ref ... OK
Testing common ... OK
Testing comment ... OK
Testing bno-symbolic ... OK
Testing dt-init ... OK
Testing ctors-dtors ... make[1]: *** [Makefile.linux:6: elf/ctors-dtors.sh] Error 1
Testing bsymbolic-functions ... OK
Testing as-needed2 ... OK
Testing as-needed-weak ... OK
Testing as-needed ... OK
Testing common-archive ... OK
Testing defs ... OK
Testing allow-multiple-definition ... OK
Testing demangle ... OK
Testing dt-needed ... OK
Testing build-id ... OK
make: *** [Makefile:129: check] Error 2
 * ERROR: sys-devel/mold-9999::gentoo failed (test phase):
 *   emake failed
```

Interestingly, if I go to the main source directory and run basic.sh, it works:
```
/var/tmp/portage/sys-devel/mold-9999/work/mold-9999 $ test/elf/basic.sh
Testing basic ... OK
```

so I assume it's to do with how it figures out where to find mold or some other build binaries?

**Comment by thesamesam** [comment]
If I run the tests outside of Portage (just from a fresh git clone), I get:
```
make -C test -f Makefile.linux --no-print-directory --output-sync
Testing aarch64-hello-static ... skipped
Testing cmdline ... OK
Testing auxiliary ... OK
Testing duplicate-error ... OK
Testing help ... OK
Testing dynamic-linker ... OK
Testing comment ... OK
Testing basic ... OK
Testing compress-debug-sections ... ./elf/compress-debug-sections.sh: line 19: dwarfdump: command not found
make[1]: *** [Makefile.linux:6: elf/compress-debug-sections.sh] Error 127
make[1]: *** Waiting for unfinished jobs....
Testing entry ... OK
Testing filter ... OK
Testing hello-dynamic ... OK
Testing exclude-libs3 ... OK
Testing empty-file ... OK
Testing empty-version ... OK
Testing discard ... OK
Testing common ... OK
Testing compressed-debug-info ..../elf/compressed-debug-info.sh: line 22: dwarfdump: command not found
make[1]: *** [Makefile.linux:6: elf/compressed-debug-info.sh] Error 127
Testing glibc-2.22-bug ... OK
Testing dynamic ... OK
Testing export-dynamic ... OK
Testing exclude-libs2 ... OK
Testing icf ... OK
Testing ar-alignment ... bfd plugin: LLVM gold plugin has failed to create LTO module: The end of the file was unexpectedly encountered
OK
Testing export-from-exe ... OK
Testing dt-init ... OK
Testing bsymbolic-functions ... OK
Testing copyrel ... OK
Testing copyrel-relro ... OK
Testing execstack ... OK
Testing gnu-warning ... OK
Testing ctors-dtors ... make[1]: *** [Makefile.linux:6: elf/ctors-dtors.sh] Error 1
Testing image-base ... OK
Testing linker-script2 ... OK
Testing bno-symbolic ... OK
Testing interpose ... OK
Testing copyrel-protected ... OK
Testing bsymbolic ... OK
Testing linker-script3 ... OK
Testing common-ref ... OK
Testing initfirst ... OK
Testing linker-script4 ... OK
Testing init-array ... OK
Testing canonical-plt ... OK
Testing ifunc-dynamic ... OK
Testing i386-hello-dynamic ... OK
Testing fatal-warnings ... OK
Testing func-addr ... mold: /home/sam/git/mold/out/test/elf/func-addr/b.o:(.text): R_X86_64_32 relocation against symbol `fn' can not be used; recompile with -fPIC
mold: /home/sam/git/mold/out/test/elf/func-addr/b.o:(.text): R_X86_64_32S relocation against symbol `fn' can not be used; recompile with -fPIC
mold: /home/sam/git/mold/out/test/elf/func-addr/b.o:(.text): R_X86_64_32 relocation against symbol `.rodata' can not be used; recompile with -fPIC
mold: /home/sam/git/mold/out/test/elf/func-addr/b.o:(.rodata): R_X86_64_64 relocation against symbol `fn' can not be used; recompile with -fPIC
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile.linux:6: elf/func-addr.sh] Error 1
Testing ifunc-export ... OK
Testing demangle ... OK
Testing linker-script ... OK
Testing as-needed ... OK
Testing as-needed-weak ... OK
Testing common-archive ... OK
Testing gnu-hash ... OK
Testing gc-sections ... OK
Testing ifunc-dso ... OK
Testing i386-tls-ld ... OK
Testing as-needed2 ... OK
Testing defs ... OK
Testing allow-multiple-definition ... OK
Testing dt-needed ... OK
Testing exclude-libs ... OK
Testing incompatible-libs ... OK
Testing i386-tls-gd ... OK
Testing init-array-priorities ... OK
Testing build-id ... OK
Testing i386-tlsdesc ... OK
Testing i386-shared ... make[1]: *** [Makefile.linux:6: elf/i386-shared.sh] Error 1
Testing ifunc-static ... OK
Testing hello-static ... OK
Testing i386-mergeable-strings ... make[1]: *** [Makefile.linux:6: elf/i386-mergeable-strings.sh] Error 1
Testing exception ... OK
Testing i386-hello-static ... OK
Testing filler ... OK
make: *** [Makefile:129: check] Error 2
```

**Comment by rui314** [comment]
I fixed a few issues in 27f72ac32030fee296c48f8d5652611aaedf9e6e. As to the mysterious failure of many tests that occurs only on `ebuild test`, it looks like mold hangs up only when it is executed by ebuild, but I couldn't figure out what causes that.

**Comment by thesamesam** [comment]
I've created a Dockerfile which may help a bit, at least:
```
FROM gentoo/stage3

# Get latest copy of the repository
RUN emerge --quiet --sync

# Allow latest version of all packages
RUN echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf

# Disable sandboxes which don't work well in Docker
RUN echo 'FEATURES="-network-sandbox -ipc-sandbox -usersandbox"' >> /etc/portage/make.conf

# Allow git version of mold
RUN echo 'sys-devel/mold **' >> /etc/portage/package.accept_keywords/mold
# Install git and mold's dependencies (not strictly necessary to do this separately)
# (just doing it so things are more separate/layered for Docker)
RUN emerge --quiet --quiet-build=y --oneshot dev-vcs/git
RUN emerge --quiet --quiet-build=y --onlydeps sys-devel/mold

# TODO: Do I need to add Clang to the test dependencies in the ebuild?
RUN emerge --quiet --quiet-build=y clang

# Allow tests (currently restricted as they don't pass for me)
RUN sed -i -e '/RESTRICT=/d' /var/db/repos/gentoo/sys-devel/mold/mold-9999.ebuild
RUN ebuild /var/db/repos/gentoo/sys-devel/mold/mold-9999.ebuild digest

# Build & test mold
CMD /bin/sh -c '. /etc/profile ; FEATURES="-sandbox -ipc-sandbox -usersandbox -pid-sandbox test" emerge --verbose sys-devel/mold'
```

Usage:
```
mkdir -p ~/docker/gentoo && cd ~/docker

# Create the attached Dockerfile
$EDITOR ~/docker/gentoo/Dockerfile

# Build the image
docker build -t gentoo gentoo/

# Run it (which builds & tries to run tests for mold)
docker run -it gentoo
```

I suspect it's to do with the path that mold is run from, but not sure.

The situation looks better now on master, but still fails the 'basic' test:
```
>>> Test phase: sys-devel/mold-9999
make -j32 SYSTEM_TBB=1 SYSTEM_MIMALLOC=1 check
make -C test -f Makefile.linux --no-print-directory --output-sync
Testing aarch64-hello-static ... skipped
Testing cmdline ... OK
Testing auxiliary ... OK
Testing duplicate-error ... OK
Testing entry ... OK
Testing basic ... make[1]: *** [Makefile.linux:6: elf/basic.sh] Error 1
make[1]: *** Waiting for unfinished jobs....
Testing discard ... OK
Testing empty-file ... OK
Testing empty-version ... OK
Testing copyrel ... OK
Testing dynamic-linker ... OK
Testing copyrel-protected ... OK
Testing copyrel-relro ... OK
Testing comment ... OK
Testing ar-alignment ... OK
Testing canonical-plt ... OK
Testing bno-symbolic ... OK
Testing common ... OK
Testing bsymbolic ... OK
Testing exclude-libs2 ... OK
Testing common-ref ... OK
Testing dynamic ... OK
Testing ctors-dtors ... make[1]: *** [Makefile.linux:6: elf/ctors-dtors.sh] Error 1
Testing bsymbolic-functions ... OK
Testing dt-init ... OK
Testing exclude-libs3 ... OK
Testing as-needed2 ... OK
Testing as-needed-weak ... OK
Testing common-archive ... OK
Testing as-needed ... OK
Testing defs ... OK
Testing allow-multiple-definition ... OK
Testing demangle ... OK
Testing exclude-libs ... OK
Testing dt-needed ... OK
Testing build-id ... OK
Testing exception ... OK
make: *** [Makefile:129: check] Error 2
 * ERROR: sys-devel/mold-9999::gentoo failed (test phase):
 *   emake failed
```

Anything more I can give?

**Comment by rui314** [comment]
I could reproduce the issue with your dockerfile, but it suddenly started succeeding except the "run" test. So, for example, "basic" now passes. Did you change something?

**Comment by thesamesam** [comment]
I didn't! But let's revisit at the point of the next release or similar given a lot has changed.
