### ISSUE TITLE
mold fails to diagnose relocation overflow

### ISSUE THREAD

**Issue by andreas-schwab** [rui314/mold#1474]
Instead of rejecting the link mold silently creates a misbehaving output.

$ cat rel.s
        .text
f:
        lla     a0,f+0x7fffffff
        ret
$ riscv64-linux-gcc -c rel.s
$ objdump -r rel.o

rel.o:     file format elf64-littleriscv

RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE              VALUE
0000000000000000 R_RISCV_PCREL_HI20  f+0x000000007fffffff
0000000000000000 R_RISCV_RELAX     *ABS*+0x000000007fffffff
0000000000000004 R_RISCV_PCREL_LO12_I  .L0 
0000000000000004 R_RISCV_RELAX     *ABS*

$ ./mold -m elf64lriscv -shared rel.o
$ objdump -d

a.out:     file format elf64-littleriscv

Disassembly of section .text:

00000000000012d0 <f>:
    12d0:       80000517                auipc   a0,0x80000
    12d4:       fff50513                addi    a0,a0,-1 # ffffffff800012cf <__bss_start+0xffffffff7fffdeff>
    12d8:       8082                    ret
$ riscv64-linux-ld -shared rel.o
rel.o: in function `f':
(.text+0x0): relocation truncated to fit: R_RISCV_PCREL_HI20 against `f'

**Comment by rui314** [comment]
Thanks, this should be addressed by the above patch.

**Comment by andreas-schwab** [comment]
Doesn't work for me, I still do not get the desired error.  Note that the
limit is 0x7ffff7ff, not 0x7fffffff, the low 12 bits are sign extended.
