### ISSUE TITLE
Support --gdb-index

### ISSUE THREAD

**Issue by rui314** [rui314/mold#396]
Currently, mold ignores `--gdb-index`. We need to support this option.

https://github.com/rui314/mold/issues/366

**Comment by rui314** [comment]
I implemented `--gdb-index`. In order to use this flag, users need to compile their object files with `-ggnu-pubnames`. I'm not 100% confident that this implementation is correct, but at least gdb doesn't complain its contents, and I can actually observe a significant speedup of gdb startup. If anyone find an odd gdb behavior that doesn't happen if you remove `--gdb-index`, please file a bug so that I can fix it.

**Comment by walkerlala** [comment]
@rui314 Hi, I got some trouble when using mold's --gdb-index feature, using gcc 7.3 and mold.

Here is how to reproduce

1.  a hello world program hw.cc
```
#include <iostream>

int main() {
  std::cout << "Hello World" << std::endl;
}
```

2. CMakeListst.txt
```
project(test1)

SET(SOURCES hw.cc)
ADD_EXECUTABLE(hw ${SOURCES})
```

3. cmake configure cmd:
```
mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS='-ggnu-pubnames' -DCMAKE_CXX_FLAGS='-ggnu-pubnames' -DCMAKE_C_LINK_FLAGS='-ggnu-pubnames -Wl,--gdb-index' -DCMAKE_CXX_LINK_FLAGS='-ggnu-pubnames -Wl,--gdb-index' ../
```

4. compile and link:
```
mold -run make -j
```

Error output:
```
[ 50%] Building CXX object CMakeFiles/hw.dir/hw.cc.o
[100%] Linking CXX executable hw
mold: error: CMakeFiles/hw.dir/hw.cc.o: --gdb-index: .debug_abbrev does not contain DW_TAG_compile_unit
mold: error: CMakeFiles/hw.dir/hw.cc.o: --gdb-index: unknown debug info form: 0x13
[100%] Built target hw
```

I am using gcc-7 from devtoolset-7 of centos7
```
> gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

But using the lastest gcc 12 snapshot (https://gcc.gnu.org/pub/gcc/snapshots/12-20220410/) still produces the same error.

Any comment ?

**Comment by rui314** [comment]
I committed a few changes to improve `--gdb-index`, so can you rebuild mold with the git head and try again?

**Comment by walkerlala** [comment]
> I committed a few changes to improve `--gdb-index`, so can you rebuild mold with the git head and try again?

This works for the small program above.

However I still encounter error below in a larger program.

```
mold: fatal: ../../IS.build/libis_all.a(easy_context.s.o): --gdb-index: unknown DWARF version 2
```

Seems like a version conflict. Any idea？

**Comment by rui314** [comment]
@walkerlala Can you try again after rebuilding mold? I'm not 100% sure if the above commit will create a correct .gdb_index, so please debug generated executable using gdb if possible.

**Comment by totph** [comment]
Now `-gdwarf-2/3` works great, however the `--gdb-index: unknown DWARF version: 33536` error (or other random numbers) also shows up when using compressed debug sections, i.e. when linking with `-gz`.

**Comment by totph** [comment]
The current main branch now works with `-gz` as well, Thank You!

**Comment by mrichtarsky** [comment]
Thanks for building this so quickly, it's appreciated :)
