### ISSUE TITLE
testsuite: ./test/elf/gdb-index-dwarf3.sh fails with fatal: /lib64/crtn.o: --gdb-index: missing debug_ranges

### ISSUE THREAD

**Issue by marxin** [rui314/mold#453]
I see the following failures:

```
$ ./test/elf/gdb-index-dwarf3.sh
Testing gdb-index-dwarf3 ... mold: fatal: /usr/lib64/crt1.o: --gdb-index: unknown debug info form: 0xf
mold: fatal: /usr/lib64/crti.o: --gdb-index: missing debug_rangescollect2: error: ld returned 1 exit status

$ readelf -SW /usr/lib64/crti.o
There are 23 section headers, starting at offset 0x608:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        0000000000000000 000040 000000 00  AX  0   0  1
  [ 2] .data             PROGBITS        0000000000000000 000040 000000 00  WA  0   0  1
  [ 3] .bss              NOBITS          0000000000000000 000040 000000 00  WA  0   0  1
  [ 4] .note.gnu.property NOTE            0000000000000000 000040 000050 00   A  0   0  8
  [ 5] .init             PROGBITS        0000000000000000 000090 000016 00  AX  0   0  4
  [ 6] .rela.init        RELA            0000000000000000 000380 000018 18   I 20   5  8
  [ 7] .fini             PROGBITS        0000000000000000 0000a8 000008 00  AX  0   0  4
  [ 8] .note.GNU-stack   PROGBITS        0000000000000000 0000b0 000000 00      0   0  1
  [ 9] .debug_line       PROGBITS        0000000000000000 0000b0 00005b 00   C  0   0  8
  [10] .rela.debug_line  RELA            0000000000000000 000398 000090 18   I 20   9  8
  [11] .debug_line_str   PROGBITS        0000000000000000 00010b 000032 01  MS  0   0  1
  [12] .debug_info       PROGBITS        0000000000000000 00013d 000023 00      0   0  1
  [13] .rela.debug_info  RELA            0000000000000000 000428 000090 18   I 20  12  8
  [14] .debug_abbrev     PROGBITS        0000000000000000 000160 000012 00      0   0  1
  [15] .debug_aranges    PROGBITS        0000000000000000 000178 000032 00   C  0   0  8
  [16] .rela.debug_aranges RELA            0000000000000000 0004b8 000048 18   I 20  15  8
  [17] .debug_str        PROGBITS        0000000000000000 0001aa 00003e 01  MS  0   0  1
  [18] .debug_rnglists   PROGBITS        0000000000000000 0001e8 000021 00      0   0  1
  [19] .rela.debug_rnglists RELA            0000000000000000 000500 000030 18   I 20  18  8
  [20] .symtab           SYMTAB          0000000000000000 000210 000138 18     21   9  8
  [21] .strtab           STRTAB          0000000000000000 000348 000032 00      0   0  1
  [22] .shstrtab         STRTAB          0000000000000000 000530 0000d4 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  D (mbind), l (large), p (processor specific)
```

**Comment by marxin** [comment]
Happens on `x86_64-linux-gnu`.

**Comment by rui314** [comment]
I believe it's caused by the previous error `unknown debug info form: 0xf`. I fixed that issue in the above commit, so please try again. Thanks!

**Comment by marxin** [comment]
Hm, updating to a8c4c71dd7710903824afd9a0dafe58a59e60567, I still see the error:

```
$ ./test/elf/gdb-index-compress-output.sh
Testing gdb-index-compress-output ... mold: fatal: /usr/lib64/crt1.o: --gdb-index: unhandled form for DW_AT_high_pc: 0xf
collect2: error: ld returned 1 exit status
```

and the `gdb-index-dwarf*` fail with:

```
Testing gdb-index-dwarf2 ... collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make[1]: *** [Makefile.linux:6: elf/gdb-index-dwarf2.sh] Error 1
Testing gdb-index-dwarf3 ... collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make[1]: *** [Makefile.linux:6: elf/gdb-index-dwarf3.sh] Error 1
Testing gdb-index-dwarf4 ... collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make[1]: *** [Makefile.linux:6: elf/gdb-index-dwarf4.sh] Error 1
Testing gdb-index-dwarf5 ... collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
```

crashes with the following backtrace:

```
(gdb) bt
#0  0x00000000004f3fc8 in mold::elf::read_rnglist_range<mold::elf::X86_64> (ctx=..., file=..., rnglist=0x80004f5f3b5f <error: Cannot access memory at address 0x80004f5f3b5f>, addrx=0x0) at elf/dwarf.cc:316
#1  0x00000000004f6de1 in mold::elf::read_address_areas<mold::elf::X86_64> (ctx=..., file=..., offset=335) at elf/dwarf.cc:417
#2  0x00000000007eeaaa in mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}::operator()(mold::elf::ObjectFile<mold::elf::X86_64>*) const (__closure=0x7fffffffb560, file=0x3d67c1b5b80) at elf/output-chunks.cc:2389
#3  0x00000000008fce01 in tbb::detail::d2::parallel_for_each_operator_selector<mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}>::call<mold::elf::ObjectFile<mold::elf::X86_64>*&, tbb::detail::d2::feeder_impl<mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*> >(mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1} const&, mold::elf::ObjectFile<mold::elf::X86_64>*&, tbb::detail::d2::feeder_impl<mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>*) (body=..., item=@0x3d67c2b0028: 0x3d67c1b5b80) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for_each.h:95
#4  0x00000000008f5b58 in tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>::operator()(tbb::detail::d1::blocked_range<unsigned long>) const (this=0x3d6b0021ad8, range=...) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for_each.h:400
#5  0x00000000008f0692 in tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>::run_body(tbb::detail::d1::blocked_range<unsigned long>&) (this=0x3d6b0021a80, r=...) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for.h:119
#6  0x00000000008e7dc4 in tbb::detail::d1::dynamic_grainsize_mode<tbb::detail::d1::adaptive_mode<tbb::detail::d1::auto_partition_type> >::work_balance<tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>, tbb::detail::d1::blocked_range<unsigned long> >(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>&, tbb::detail::d1::blocked_range<unsigned long>&, tbb::detail::d1::execution_data&) (this=0x3d6b0021af8, start=warning: RTTI symbol not found for class 'tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>'
..., range=..., ed=...) at third-party/tbb/include/tbb/../oneapi/tbb/partitioner.h:447
#7  0x00000000008e0b1e in tbb::detail::d1::partition_type_base<tbb::detail::d1::auto_partition_type>::execute<tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>, tbb::detail::d1::blocked_range<unsigned long> >(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>&, tbb::detail::d1::blocked_range<unsigned long>&, tbb::detail::d1::execution_data&) (this=0x3d6b0021af8, start=warning: RTTI symbol not found for class 'tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>'
..., range=..., ed=...) at third-party/tbb/include/tbb/../oneapi/tbb/partitioner.h:288
#8  0x00000000008dc596 in tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::write_address_areas(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>::execute(tbb::detail::d1::execution_data&) (this=0x3d6b0021a80, ed=...) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for.h:172
#9  0x0000000000b9149a in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter> (waiter=..., t=0x3d6b0021a80, this=0x3d67c292080) at /home/marxin/Programming/mold/third-party/tbb/src/tbb/task_dispatcher.h:322
#10 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter> (waiter=..., t=0x0, this=0x3d67c292080) at /home/marxin/Programming/mold/third-party/tbb/src/tbb/task_dispatcher.h:463
#11 tbb::detail::r1::arena::process (this=<optimized out>, tls=...) at /home/marxin/Programming/mold/third-party/tbb/src/tbb/arena.cpp:138
#12 0x0000000000b9f20b in tbb::detail::r1::market::process (this=0x3d67c0d0a80, j=...) at /home/marxin/Programming/mold/third-party/tbb/src/tbb/market.cpp:597
#13 0x0000000000ba1ed4 in tbb::detail::r1::rml::private_worker::run (this=0x3d67c217a00) at /home/marxin/Programming/mold/third-party/tbb/src/tbb/private_server.cpp:267
#14 0x0000000000ba2129 in tbb::detail::r1::rml::private_worker::thread_routine (arg=<optimized out>) at /home/marxin/Programming/mold/third-party/tbb/src/tbb/private_server.cpp:221
#15 0x00007ffff77772ba in start_thread (arg=<optimized out>) at pthread_create.c:442
#16 0x00007ffff7801460 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

...
(gdb) p file->filename
$2 = "/usr/lib64/gcc/x86_64-suse-linux/11/../../../../lib64/crtn.o"
```
