### ISSUE TITLE
Linking with a specified common and max page size is broken

### ISSUE THREAD

**Issue by ms178** [rui314/mold#732]
@rui314 Very recently linking with mold-git and a specified page size (I usually use -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000) got broken, I suspect https://github.com/rui314/mold/commit/2941d75c717279fcb1df23acf4ed911b3d1e4daa or related changes from today to be the culprit. 

With both GCC 12.2.1 and a snapshot from today of Clang-16, I now get errrors like `/usr/bin/ld.mold: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory` when trying to compile with these flags and mold.

This also happens when compiling mold-git itself. I have just tested it, mold-git works fine when it is compiled without `-Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000` but then starts to error out when using it with `-Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000`.

**Comment by ms178** [comment]
By the way, using these flags works fine with mold-1.4.2, albeit as noted in the linked committ, the binary size is significantly larger than what other linkers produce with the same flags.

**Comment by rui314** [comment]
Thank you for your report! I fixed the issue in the above commit.

**Comment by ms178** [comment]
@rui314 Thanks for taking a look, but it is still broken. I've just tried it with compiling with clang-16 and mold 1.4.2 > 1.5.0 (works fine) and 1.5.0 > 1.5.0 (compiles fine but the result is a broken mold as using that second one again for 1.5.0 > 1.5.0 is now broken).

**Comment by rui314** [comment]
I built mold 1.5.0 using 1.4.2 with `-z max-page-size=0x200000` and then build 1.5.0 again using 1.5.0 with the same flag. All the output files work just fine (all tests pass). What am I missing? Did you still get the same error?

**Comment by ms178** [comment]
I've used `-Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000` and could replicate my findings.

Here is my PKGBUILD:
[PKGBUILD.txt](https://github.com/rui314/mold/files/9653784/PKGBUILD.txt)

My flags in makepkg.conf:

```
export CC=clang
export CXX=clang++
export CC_LD=mold
export CXX_LD=mold
export AR=llvm-ar
export NM=llvm-nm
export STRIP=llvm-strip
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export RANLIB=llvm-ranlib
export HOSTCC=clang
export HOSTCXX=clang++
export HOSTAR=llvm-ar
export CFLAGS="-O3 -march=native -mllvm -polly -mllvm -polly-position=early -mllvm -polly-parallel=true -fopenmp -fopenmp-version=50 -mllvm -polly-dependences-computeout=5000000 -mllvm -polly-detect-profitability-min-per-loop-insts=40 -mllvm -polly-tiling=true -mllvm -polly-prevect-width=256 -mllvm -polly-vectorizer=stripmine -mllvm -polly-omp-backend=LLVM -mllvm -polly-num-threads=36 -mllvm -polly-scheduling=dynamic -mllvm -polly-scheduling-chunksize=1 -mllvm -polly-ast-use-context -mllvm -polly-invariant-load-hoisting -mllvm -polly-loopfusion-greedy -mllvm -polly-run-inliner -mllvm -polly-run-dce -mllvm -polly-enable-delicm=true -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -fno-math-errno -fno-trapping-math -funroll-loops -falign-functions=32 -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -flto"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000"
```

**Comment by rui314** [comment]
I still can't reproduce it locally. Can you share your mold executable that didn't work due to the `error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory` error?

**Comment by ms178** [comment]
With the new PKGBUILD and my flags I get:

99% tests passed, 3 tests failed out of 273

Total Test time (real) =  15.63 sec

The following tests FAILED:
         30 - x86_64-debug-macro-section.sh (Failed)
        146 - x86_64-pltgot-x86-64.sh (Failed)
        155 - x86_64-relax.sh (Failed)

**Comment by ms178** [comment]
The new PKGBUILD uses the CMAKE-buildsystem. It seems to be a problem with Clang, as all tests pass with GCC and the following flags:

```
CFLAGS="-O3 -march=native -fno-semantic-interposition -falign-functions=32 -fipa-pta -flive-range-shrinkage -fno-math-errno -fno-trapping-math -mtls-dialect=gnu2 -feliminate-unused-debug-types -floop-nest-optimize -fgraphite-identity -fcf-protection=none -pipe -flto=auto -floop-parallelize-all -ftree-parallelize-loops=18 -fdevirtualize-at-ltrans -mharden-sls=none -funroll-loops -malign-data=cacheline -fomit-frame-pointer"
CXXFLAGS="$CFLAGS"
LDFLAGS="-Wl,-O3,--as-needed,-Bsymbolic-functions,-flto=auto -fopenmp -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000"
CCLDFLAGS="-Wl,-O3,--as-needed,-Bsymbolic-functions,-flto=auto -fopenmp -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000"
CXXLDFLAGS="-Wl,-O3,--as-needed,-Bsymbolic-functions,-flto=auto -fopenmp -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000"
ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -msse2avx -D__FMA__=1"
LTOFLAGS="-flto=auto"


```

**Comment by rui314** [comment]
Hmm, I don't know why, but your executable was indeed built by mold 1.5.0 and didn't have a desired memory layout. I think I need to reproduce it on my machine using Docker. Can you show me your distro name and version number?

**Comment by ms178** [comment]
I've re-compiled Zstd with GCC as well to eliminate hidden errors in the dependancies, but that did not help.

My distribution is CachyOS:
https://sourceforge.net/projects/cachyos-arch/files/gui-installer/kde/

**Comment by ptr1337** [comment]
> Hmm, I don't know why, but your executable was indeed built by mold 1.5.0 and didn't have a desired memory layout. I think I need to reproduce it on my machine using Docker. Can you show me your distro name and version number?

Actually im the maintainer of CachyOS. He did wrote the about the issue.
I was able to reproduce the issue, compiled with GCC and as linker was MOLD used. 

I was able to reproduce the issue with FLAGS he posted here:
https://github.com/rui314/mold/issues/732#issuecomment-1259228785

Build log:
```
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for zstd.h
-- Looking for zstd.h - found
-- Performing Test I386
-- Performing Test I386 - Failed
-- Looking for pow in m
-- Looking for pow in m - found
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1q") found components: Crypto 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/makepkg/mold-git/src/build
[  1%] Building C object CMakeFiles/mold-wrapper.dir/elf/mold-wrapper.c.o
[  1%] Built target git_hash
[  2%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.I386.cc.o
[  2%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.ARM64.cc.o
[  2%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.X86_64.cc.o
[  2%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.RV32LE.cc.o
[  4%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.RV32BE.cc.o
[  4%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.ARM32.cc.o
[  4%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.RV64LE.cc.o
[  5%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.SPARC64.cc.o
[  5%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.X86_64.cc.o
[  6%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.PPC64V2.cc.o
[  6%] Building CXX object CMakeFiles/mold.dir/elf/cmdline.cc.RV64BE.cc.o
[  7%] Linking C shared library mold-wrapper.so
[  7%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.RV64LE.cc.o
[  9%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.I386.cc.o
[  9%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.ARM32.cc.o
[ 10%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.RV32BE.cc.o
[ 10%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.RV32LE.cc.o
[ 10%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.ARM64.cc.o
[ 11%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.RV64BE.cc.o
[ 11%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.PPC64V2.cc.o
[ 11%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.X86_64.cc.o
[ 12%] Building CXX object CMakeFiles/mold.dir/elf/dwarf.cc.SPARC64.cc.o
[ 13%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.I386.cc.o
[ 13%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.ARM64.cc.o
/usr/bin/ld.mold: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory
collect2: error: ld returned 127 exit status
make[2]: *** [CMakeFiles/mold-wrapper.dir/build.make:97: mold-wrapper.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:157: CMakeFiles/mold-wrapper.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 14%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.ARM32.cc.o
[ 14%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.RV32LE.cc.o
[ 15%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.RV32BE.cc.o
[ 15%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.RV64LE.cc.o
[ 16%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.RV64BE.cc.o
[ 16%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.PPC64V2.cc.o
[ 17%] Building CXX object CMakeFiles/mold.dir/elf/gc-sections.cc.SPARC64.cc.o
[ 17%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.X86_64.cc.o
[ 18%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.I386.cc.o
[ 19%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.ARM64.cc.o
[ 19%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.ARM32.cc.o
[ 20%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.RV32BE.cc.o
[ 20%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.RV32LE.cc.o
[ 21%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.RV64LE.cc.o
[ 21%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.RV64BE.cc.o
[ 22%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.PPC64V2.cc.o
[ 22%] Building CXX object CMakeFiles/mold.dir/elf/icf.cc.SPARC64.cc.o
[ 23%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.X86_64.cc.o
[ 23%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.I386.cc.o
[ 24%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.ARM64.cc.o
[ 24%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.ARM32.cc.o
[ 25%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.RV32LE.cc.o
[ 25%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.RV32BE.cc.o
[ 26%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.RV64LE.cc.o
[ 26%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.RV64BE.cc.o
[ 27%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.PPC64V2.cc.o
[ 27%] Building CXX object CMakeFiles/mold.dir/elf/input-files.cc.SPARC64.cc.o
[ 28%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.X86_64.cc.o
[ 28%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.I386.cc.o
[ 29%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.ARM64.cc.o
[ 29%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.ARM32.cc.o
[ 30%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.RV32LE.cc.o
[ 30%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.RV32BE.cc.o
[ 31%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.RV64LE.cc.o
[ 31%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.RV64BE.cc.o
[ 32%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.PPC64V2.cc.o
[ 32%] Building CXX object CMakeFiles/mold.dir/elf/input-sections.cc.SPARC64.cc.o
[ 33%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.X86_64.cc.o
[ 33%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.I386.cc.o
[ 34%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.ARM64.cc.o
[ 34%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.ARM32.cc.o
[ 35%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.RV32LE.cc.o
[ 36%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.RV32BE.cc.o
[ 36%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.RV64LE.cc.o
[ 37%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.RV64BE.cc.o
[ 37%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.PPC64V2.cc.o
[ 38%] Building CXX object CMakeFiles/mold.dir/elf/linker-script.cc.SPARC64.cc.o
[ 38%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.X86_64.cc.o
[ 39%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.I386.cc.o
[ 39%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.ARM64.cc.o
[ 40%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.ARM32.cc.o
[ 40%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.RV32LE.cc.o
[ 41%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.RV32BE.cc.o
[ 41%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.RV64LE.cc.o
[ 42%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.RV64BE.cc.o
[ 42%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.PPC64V2.cc.o
[ 43%] Building CXX object CMakeFiles/mold.dir/elf/lto.cc.SPARC64.cc.o
[ 43%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.X86_64.cc.o
[ 44%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.I386.cc.o
[ 44%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.ARM64.cc.o
[ 45%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.ARM32.cc.o
[ 45%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.RV32LE.cc.o
[ 46%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.RV32BE.cc.o
[ 46%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.RV64LE.cc.o
[ 47%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.RV64BE.cc.o
[ 47%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.PPC64V2.cc.o
[ 48%] Building CXX object CMakeFiles/mold.dir/elf/main.cc.SPARC64.cc.o
[ 48%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.X86_64.cc.o
[ 49%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.I386.cc.o
[ 49%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.ARM64.cc.o
[ 50%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.ARM32.cc.o
[ 50%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.RV32LE.cc.o
[ 51%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.RV32BE.cc.o
[ 52%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.RV64LE.cc.o
[ 52%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.RV64BE.cc.o
[ 53%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.PPC64V2.cc.o
[ 53%] Building CXX object CMakeFiles/mold.dir/elf/mapfile.cc.SPARC64.cc.o
[ 54%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.X86_64.cc.o
[ 54%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.I386.cc.o
[ 55%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.ARM64.cc.o
[ 55%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.ARM32.cc.o
[ 56%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.RV32LE.cc.o
[ 56%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.RV32BE.cc.o
[ 57%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.RV64LE.cc.o
[ 57%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.RV64BE.cc.o
[ 58%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.PPC64V2.cc.o
[ 58%] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.SPARC64.cc.o
[ 59%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.X86_64.cc.o
[ 59%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.I386.cc.o
[ 60%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.ARM64.cc.o
[ 60%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.ARM32.cc.o
[ 61%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.RV32LE.cc.o
[ 61%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.RV32BE.cc.o
[ 62%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.RV64LE.cc.o
[ 62%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.RV64BE.cc.o
[ 63%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.PPC64V2.cc.o
[ 63%] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.SPARC64.cc.o
[ 64%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.X86_64.cc.o
[ 64%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.I386.cc.o
[ 65%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.ARM64.cc.o
[ 65%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.ARM32.cc.o
[ 66%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.RV32LE.cc.o
[ 66%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.RV32BE.cc.o
[ 67%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.RV64LE.cc.o
[ 67%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.RV64BE.cc.o
[ 68%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.PPC64V2.cc.o
[ 69%] Building CXX object CMakeFiles/mold.dir/elf/relocatable.cc.SPARC64.cc.o
[ 69%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.X86_64.cc.o
[ 70%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.I386.cc.o
[ 70%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.ARM64.cc.o
[ 71%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.ARM32.cc.o
[ 71%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.RV32LE.cc.o
[ 72%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.RV32BE.cc.o
[ 72%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.RV64LE.cc.o
[ 73%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.RV64BE.cc.o
[ 73%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.PPC64V2.cc.o
[ 74%] Building CXX object CMakeFiles/mold.dir/elf/subprocess.cc.SPARC64.cc.o
[ 74%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.X86_64.cc.o
[ 75%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.I386.cc.o
[ 75%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.ARM64.cc.o
[ 76%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.ARM32.cc.o
[ 76%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.RV32LE.cc.o
[ 77%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.RV32BE.cc.o
[ 77%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.RV64LE.cc.o
[ 78%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.RV64BE.cc.o
[ 78%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.PPC64V2.cc.o
[ 79%] Building CXX object CMakeFiles/mold.dir/elf/thunks.cc.SPARC64.cc.o
[ 79%] Building CXX object CMakeFiles/mold.dir/macho/cmdline.cc.X86_64.cc.o
[ 80%] Building CXX object CMakeFiles/mold.dir/macho/cmdline.cc.ARM64.cc.o
[ 80%] Building CXX object CMakeFiles/mold.dir/macho/dead-strip.cc.X86_64.cc.o
[ 81%] Building CXX object CMakeFiles/mold.dir/macho/dead-strip.cc.ARM64.cc.o
[ 81%] Building CXX object CMakeFiles/mold.dir/macho/input-files.cc.X86_64.cc.o
[ 82%] Building CXX object CMakeFiles/mold.dir/macho/input-files.cc.ARM64.cc.o
[ 82%] Building CXX object CMakeFiles/mold.dir/macho/input-sections.cc.X86_64.cc.o
[ 83%] Building CXX object CMakeFiles/mold.dir/macho/input-sections.cc.ARM64.cc.o
[ 83%] Building CXX object CMakeFiles/mold.dir/macho/lto.cc.X86_64.cc.o
[ 84%] Building CXX object CMakeFiles/mold.dir/macho/lto.cc.ARM64.cc.o
[ 84%] Building CXX object CMakeFiles/mold.dir/macho/main.cc.X86_64.cc.o
[ 85%] Building CXX object CMakeFiles/mold.dir/macho/main.cc.ARM64.cc.o
[ 86%] Building CXX object CMakeFiles/mold.dir/macho/mapfile.cc.X86_64.cc.o
[ 86%] Building CXX object CMakeFiles/mold.dir/macho/mapfile.cc.ARM64.cc.o
[ 87%] Building CXX object CMakeFiles/mold.dir/macho/output-chunks.cc.X86_64.cc.o
[ 87%] Building CXX object CMakeFiles/mold.dir/macho/output-chunks.cc.ARM64.cc.o
[ 88%] Building CXX object CMakeFiles/mold.dir/macho/tapi.cc.X86_64.cc.o
[ 88%] Building CXX object CMakeFiles/mold.dir/macho/tapi.cc.ARM64.cc.o
[ 89%] Building CXX object CMakeFiles/mold.dir/compress.cc.o
[ 89%] Building CXX object CMakeFiles/mold.dir/demangle.cc.o
[ 90%] Building CXX object CMakeFiles/mold.dir/elf/arch-arm32.cc.o
[ 90%] Building CXX object CMakeFiles/mold.dir/elf/arch-arm64.cc.o
[ 91%] Building CXX object CMakeFiles/mold.dir/elf/arch-i386.cc.o
[ 91%] Building CXX object CMakeFiles/mold.dir/elf/arch-ppc64v2.cc.o
[ 92%] Building CXX object CMakeFiles/mold.dir/elf/arch-riscv.cc.o
[ 92%] Building CXX object CMakeFiles/mold.dir/elf/arch-sparc64.cc.o
[ 93%] Building CXX object CMakeFiles/mold.dir/elf/arch-x86-64.cc.o
[ 93%] Building CXX object CMakeFiles/mold.dir/filepath.cc.o
[ 94%] Building CXX object CMakeFiles/mold.dir/git-hash.cc.o
[ 94%] Building CXX object CMakeFiles/mold.dir/glob.cc.o
[ 95%] Building CXX object CMakeFiles/mold.dir/hyperloglog.cc.o
[ 95%] Building CXX object CMakeFiles/mold.dir/macho/arch-arm64.cc.o
[ 96%] Building CXX object CMakeFiles/mold.dir/macho/arch-x86-64.cc.o
[ 96%] Building CXX object CMakeFiles/mold.dir/macho/yaml.cc.o
[ 97%] Building CXX object CMakeFiles/mold.dir/main.cc.o
[ 97%] Building CXX object CMakeFiles/mold.dir/multi-glob.cc.o
[ 98%] Building CXX object CMakeFiles/mold.dir/perf.cc.o
[ 98%] Building CXX object CMakeFiles/mold.dir/strerror.cc.o
[ 99%] Building CXX object CMakeFiles/mold.dir/tar.cc.o
[ 99%] Building C object CMakeFiles/mold.dir/third-party/rust-demangle/rust-demangle.c.o
[100%] Building CXX object CMakeFiles/mold.dir/uuid.cc.o
[100%] Linking CXX executable mold
/usr/bin/ld.mold: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory
collect2: error: ld returned 127 exit status
make[2]: *** [CMakeFiles/mold.dir/build.make:3143: mold] Error 1
make[1]: *** [CMakeFiles/Makefile2:131: CMakeFiles/mold.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

```

I was able to reproduce this issue also on a arch linux docker image.
Since we currently don't provide a docker images, I have just tested it in a archlinux one, since we are a archlinux based distro.
We are recompiling, all archlinux packages in x86-64-v3, otherwise there is no difference mostly to the packages.

**Comment by ptr1337** [comment]
Anyways, our builds with the default Flags went without problems, also check worked without any issue.

**Comment by ptr1337** [comment]
Actually it seems that `-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000` does bring the issue right now, if mold gets linked at the second compilation.

Removing this flags, compiling them with the exactly same just the page-size flags removed, mold compiles the second time correctly and all checks are passsing

**Comment by rui314** [comment]
I don't know how to build a package on Arch as I'm not familiar with that distro. Do you mind if I ask you to archive your entire build directory of mold and share it with me? I don't think I can't fix this issue without trial-and-error, so I need to build it myself on my local machine.

**Comment by OfekShochat** [comment]
on arch, if you have the PKGBUILD its as easy as executing `makepkg`

**Comment by rui314** [comment]
But that PKGBUILD doesn't include any `max-page-size` option, so there must be something hidden.

**Comment by ms178** [comment]
@rui314 It's super easy actually. The compilation flags are handled in the /etc/makepkg.conf file. Just copy my entries from https://github.com/rui314/mold/issues/732#issuecomment-1259228785 into it overwriting the defaults. Then do a makepkg -si from the console within in the mold-git directory where the PKGBUILD is. Et voila, it should pull in all dependancies automatically with that command.

**Comment by rui314** [comment]
This looks like a critical issue, and I don't know how to fix it immediately. I'll revert my recent commits related to memory layout change, test it and then release it as 1.5.1. I'll fix this issue after that.

**Comment by sicherha** [comment]
Could you give the commit range? I have a Raspberry Pi 4 at hand and may be able to help bisect.

**Comment by rui314** [comment]
I have a Raspberry Pi 4 too, and I'm sure that the commits after 34e2c087326a978e77ed57326debe978ae5ba69a caused the regression.

**Comment by sicherha** [comment]
Commit 34e2c087326a978e77ed57326debe978ae5ba69a doesn't seem to exist on GitHub.

**Comment by rui314** [comment]
Sorry I mean 9c7b95f108bb1b72eb61d2255c42df712f1c5757

**Comment by rui314** [comment]
I will release 1.5.1 tomorrow with the current git head if it works OK, so please check it out and see if it fixes your issue. Thanks!

**Comment by ms178** [comment]
@rui314 I've just tested current git head with GCC and the specified page size and it works fine again with that revert. Thanks!

**Comment by sicherha** [comment]
Bisection result:
> 9c7b95f108bb1b72eb61d2255c42df712f1c5757 is the first bad commit

**Comment by rui314** [comment]
Right. I'll revert all these changes for now and will fix it after 1.5.1.

**Comment by rui314** [comment]
@ms178 
> It's super easy actually. The compilation flags are handled globally in the /etc/makepkg.conf file. Just copy my entries from https://github.com/rui314/mold/issues/732#issuecomment-1259228785 into it, overwriting the defaults. Then do a makepkg -si from the console within in the mold-git directory where the PKGBUILD is.

Well it's not actually super easy for those who don't know really anything about arch. I don't know what `mold-git` directory is. Does this mean a directory created by `git pull https://github.com/rui314/mold.git` or something else?

**Comment by ms178** [comment]
> @ms178
> 
> > It's super easy actually. The compilation flags are handled globally in the /etc/makepkg.conf file. Just copy my entries from [#732 (comment)](https://github.com/rui314/mold/issues/732#issuecomment-1259228785) into it, overwriting the defaults. Then do a makepkg -si from the console within in the mold-git directory where the PKGBUILD is.
> 
> Well it's not actually super easy for those who don't know really anything about arch. I don't know what `mold-git` directory is. Does this mean a directory created by `git pull https://github.com/rui314/mold.git` or something else?

The build process for custom packages from the AUR on Arch is well documented (https://wiki.archlinux.org/title/makepkg). You need to download a file containing the PKGBUILD (which is the build recipe for a program) and extract it, typically the folder is named after the program. For mold-git, simply donwload and extract the PKGBUILD from here: https://aur.archlinux.org/cgit/aur.git/snapshot/mold-git.tar.gz

You'd need the prerequisites to use makepkg and I already mentioned the command how to obtain them. Then you simply run `makepkg -si` from a console within the mold-git directory where you extracted the PKGBUILD to. That's all, makepkg should pull in all dependancies by itself automatically and start the compilation process with the flags which are set in /etc/makepkg.conf.

**Comment by rui314** [comment]
OK, so it looks like it's `strip` who broke mold-generated output files. If you do not run `strip`, mold's output should work. It seems a `strip`'s bug, but I think we need to make a change to our side so that it becomes bug-compatible. I'll make such a change.
